# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Uses default location of GitHub Workflows
    schedule:
      interval: "weekly"
    groups:
      prod-github-actions:
        dependency-type: "production"
      dev-github-actions:
        dependency-type: "development"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/complete-application/"
    schedule:
      interval: "weekly"
    groups:
      prod-npm-minor-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-npm-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
